cookie:
  expiry_days: 30
  key: random_signature_key_12345
  name: squeeze_ai_cookie
credentials:
  usernames:
    mlbant:
      email: acusumano618@gmail.com
      failed_login_attempts: 0
      first_name: Anthony
      last_name: Cusumano
      logged_in: false
      password: $2b$12$6qRHZrg.xyLAO0r4iV4LyeQscvk3559mLlDtKXxgBj6pBmAZ/DG92
      roles: null
    mlbant13:
      email: acusumano618@googlemail.com
      failed_login_attempts: 0
      first_name: Anthony
      last_name: Cusumano
      logged_in: false
      password: $2b$12$wmYZLkGqv97r75VdPrNElO4YDESLGA9hbMoTliV0aLztNscpaMjZ.
      roles: null
preauthorized:
  emails: []
reset_tokens: {}